# Generated by Django 5.1 on 2025-05-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_sessionsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=50),
        ),
    ]
