# Generated by Django 5.1 on 2025-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_student_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
