# Generated by Django 5.1 on 2025-06-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_homeworksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionwithimage',
            name='level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
