# Generated by Django 5.1 on 2025-06-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_worksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionwithimage',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
